
substitutions:
  device_name: "esp32cam"
  friendly_name: Wifi Camera
  device_description: Basic WIFI camera in an default ESP32-CAM module.

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}


esp32:
  board: esp32cam
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "hX3hqBj3Ut60"

captive_portal:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 16MHz  # default 20MHz. Supposedly 10MHz will increase FPS perf, but maybe not the case in esphome?
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  name: $friendly_name
  icon: mdi:video-wireless
  resolution: 1024x768 # you can use: [1600x1200 , 1280x1024 , 1024x768 , 800x600, 640x480 ] for best performance (FPS) use 1024 or lower resolution.
  
  jpeg_quality: 20  # The JPEG quality that the camera should encode images with. From 10 (best) to 63 (worst)
  aec2: true        # enable Auto Exposure Control 2 - changes AE computation method
  ae_level: 2       # auto exposure level, defaults 0
  brightness: 2     # The brightness to apply to the picture, default 0, updated to 2 for birdhouse

# http server setting
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
    
# Flashlight, use channel 2 for PWM, channel 1 is used by camera.
output:
  - platform: ledc
    pin: GPIO4
    id: gpio_4
    channel: 2

## GPIO_4 is the flash light pin
light:
  - platform: monochromatic
    output: gpio_4
    name: PWM light

switch:
  - platform: restart
    name: "${device_name} restart"   
    entity_category: config

sensor:
  - platform: uptime
    name: $device_name Uptime
    disabled_by_default: true
    entity_category: diagnostic  
    
  - platform: wifi_signal
    name: $device_name WiFi Signal
    update_interval: 240s
    disabled_by_default: true
    entity_category: diagnostic  

  - platform: internal_temperature
    name: "cpu Temperature"
    internal: true