# This one has a CO2 sensor
substitutions:
  name: apollo-msr-bedroom
  friendly_name: MSR Bedroom
packages:
  ApolloAutomation.MSR-2: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: BAb5mbT+ixbN0iKvpfHNMz6r7qR6/UKQnTEVCoxnDO4=


wifi:
  # Power saving for BLE proxy
  power_save_mode: LIGHT
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: apollo-msr-2-0458dc.local

# Enable BLE proxy settings for Home Assistant
bluetooth_proxy:
  active: true
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false