substitutions:
  name: apollo-msr-living-room
  friendly_name: MSR Living Room
packages:
  ApolloAutomation.MSR-2: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 9NY5eJpp0AfmOIWlBm0fS/aM4Q8zLZl0DtzxaeuV69s=

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: apollo-msr-2-0badb8.local