substitutions:
  name: dishwasher-plug
  friendly_name: Dishwasher Plug
  room: "kitchen"
  dns_domain: ".local"
  relay_restore_mode: RESTORE_DEFAULT_ON
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: yf/Eup3B3AFNWRywaK/2hm+58lD5M0YdScAWsF2wwc8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: athom-smart-plug-v2-a794a1.local
