substitutions:
  name: ventilation-plug
  friendly_name: Ventilation Plug
  room: "bathroom"
  dns_domain: ".local"
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  # athom.smart-plug-v2-modified: github://OACDesigns/athom-configs/athom-smart-plug-v2.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

# NB: when using mqtt instead of native api, this must be removed otherwise the ESP will reboot every 15 mins
api:
  encryption:
    key: D1oLn7BUFwne8iUZ3zdYgI5IPSyxIPnYiby3leqgQsI=

# mqtt:
#   broker: !secret mqtt_broker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # manual_ip:
  #   static_ip: 192.168.1.112
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0