substitutions:
  name: oven-plug
  friendly_name: Oven Plug
  room: "kitchen"
  dns_domain: ".local"
  relay_restore_mode: RESTORE_DEFAULT_ON
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  # athom.smart-plug-v2: github://OACDesigns/athom-configs/athom-smart-plug-v2.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: gvMiAISbSCCYNBtdRA6pAo4J6A/zDTtITw3YFJnB0Rc=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
