substitutions:
  name: m5stack-atom-echo-b83894
  friendly_name: M5Stack Atom Echo b83894
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.adopted.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: KTlfQUUKARLoQIaQqRikJBXzSiJIzORRrCI3lLldAs4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# workaround for failing compilation
esp32:
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0