substitutions:
  name: slimmelezer
packages:
  zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: t4z6TxQiRJLgCUDdVdatHOsxb4a1RtcPoVFWL+NDt5Y=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
